### ISSUE TITLE
Question about the `actions/checkout` example

### ISSUE THREAD

**Issue by julienma** [obrassard/action-dokku-deploy#3]
Hey @obrassard, quick question about the `checkout` action in your example workflow:

```yml
    - name: Cloning repo # This step is required
      uses: actions/checkout@v2

    # This step is required or you might get an error from Dokku
    - run: git fetch --prune --unshallow 
```

You use the `git fetch --prune --unshallow`, whereas [other](https://github.com/marketplace/actions/dokku-deploy-action) [actions](https://github.com/marketplace/actions/easily-dokku-deploy) I saw use this:

```yml
    - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

Why did you chose to do that? Is there any difference?
Thanks
